services:
  server:
    build:
      dockerfile: ./server.Dockerfile
    ports:
      - ${SERVER_EXTERNAL_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_ANSWER_TIMEOUT=${CLIENT_ANSWER_TIMEOUT}

  client:
    build:
      dockerfile: ./client.Dockerfile
    depends_on:
      - server
    restart: always
    environment:
      - SERVER_ADDR=server:${SERVER_PORT}
    command: ["bash", "-c", "./client && sleep 2"]
